name: Auto Merge Shadowrocket Config

on:
  schedule:
    # 每天 UTC 时间 20:00 (北京时间凌晨 04:00) 自动运行一次
    - cron: '0 20 * * *'
  # 支持在 GitHub 页面手动点击触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.x'

      - name: Run Build Script
        run: python build_config.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add shadow.conf
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: 自动同步合并最新上游规则" && git push)
